#!/usr/bin/env python3
"""Replay one saved native Cartesian planning request without robot hardware.

Each invocation deliberately runs exactly one configuration.  A CUDA illegal
instruction poisons the process context, so compare variants by launching a
fresh process for every row, for example::

    CUDA_LAUNCH_BLOCKING=1 python src/validation/planning/diagnose_native_pose_cuda.py \
        --request /path/planning_debug/123.npz --hand fr3_inspire \
        --mode cartesian --cuda-graph off --lock-hand on

The adjacent ``*_scene.json`` generated by ``plan_cartesian_pose`` or
``plan_pose_constrained`` is selected automatically when present.  No camera,
robot, or executor is initialized by this script.

The same command also replays ``vertical_*.npz`` dumps emitted by
``plan_vertical_stroke``.  ``--mode auto`` recognizes their signed Jacobian
request and reports continuation/retiming/final-validation details.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np


def _bool_arg(value: str) -> bool:
    parsed = value.strip().lower()
    if parsed in {"on", "true", "1", "yes"}:
        return True
    if parsed in {"off", "false", "0", "no"}:
        return False
    raise argparse.ArgumentTypeError("expected one of on/off, true/false, 1/0")


def _scalar_text(value) -> str:
    if isinstance(value, np.ndarray):
        value = value.reshape(-1)[0]
    if isinstance(value, bytes):
        value = value.decode("utf-8")
    return str(value)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--request", type=Path, required=True,
                        help="planner debug .npz request")
    parser.add_argument("--scene", type=Path,
                        help="scene JSON; defaults to <request>_scene.json")
    parser.add_argument("--hand", default="fr3_inspire",
                        help="GraspPlanner hand/robot configuration")
    parser.add_argument("--mode", choices=("auto", "cartesian", "constrained", "vertical"),
                        default="auto")
    parser.add_argument("--cuda-graph", type=_bool_arg, default=True)
    parser.add_argument("--lock-hand", type=_bool_arg, default=True)
    args = parser.parse_args()

    if os.environ.get("CUDA_LAUNCH_BLOCKING") != "1":
        print("[diagnose] warning: set CUDA_LAUNCH_BLOCKING=1 before Python "
              "to identify the first failing CUDA call", file=sys.stderr)

    request_path = args.request.resolve()
    scene_path = args.scene
    if scene_path is None:
        scene_path = request_path.with_name(f"{request_path.stem}_scene.json")
    scene_path = scene_path.resolve()
    if not request_path.is_file() or not scene_path.is_file():
        parser.error(f"request/scene pair is required: {request_path}, {scene_path}")

    with np.load(request_path, allow_pickle=False) as request:
        start_full = np.asarray(request["start_full_qpos"], dtype=np.float32)
        is_vertical_request = "wrist_end" in request.files
        target = np.asarray(
            request["wrist_end" if is_vertical_request else "target_wrist_pose"],
            dtype=np.float32)
        wrist_start = (np.asarray(request["wrist_start"], dtype=np.float32)
                       if is_vertical_request else None)
        mask = (np.asarray(request["hold_vec_weight"], dtype=np.float32)
                if "hold_vec_weight" in request.files
                else np.asarray([1, 1, 1, 1, 1, 0], dtype=np.float32))
        recorded_mode = _scalar_text(request["constraint_mode"])
        include_obj = bool(np.asarray(request["include_obj_obstacle"]).item())
        expected_travel = (float(np.asarray(request["expected_travel_m"]).item())
                           if "expected_travel_m" in request.files else None)
        attached_object_pose = None
        if "attached_object_pose_at_start" in request.files:
            saved_attached = np.asarray(
                request["attached_object_pose_at_start"], dtype=np.float64)
            if saved_attached.shape == (4, 4):
                attached_object_pose = saved_attached
    with scene_path.open(encoding="utf-8") as stream:
        scene_cfg = json.load(stream)

    mode = recorded_mode if args.mode == "auto" else args.mode
    if mode == "native_cartesian":
        mode = "cartesian"
    if mode == "endpoint_approximation":
        mode = "cartesian"
    if mode == "native_strict":
        mode = "constrained"
    if mode == "jacobian_vertical_stroke":
        mode = "vertical"
    if mode not in {"cartesian", "constrained", "vertical"}:
        parser.error(f"unrecognized recorded constraint_mode={recorded_mode!r}")
    if mode == "constrained" and not np.any(mask):
        parser.error("constrained replay requires a request with a non-zero hold mask")

    # Import after argument parsing so the error message above is available
    # even on hosts without the project CUDA environment.
    repo_root = Path(__file__).resolve().parents[3]
    sys.path.insert(0, str(repo_root))
    from autodex.planner import CudaPlanningFault, GraspPlanner

    planner = GraspPlanner(hand=args.hand, use_cuda_graph=args.cuda_graph,
                           verbose_planning=True)
    print("[diagnose] "
          f"mode={mode} graph={args.cuda_graph} lock_hand={args.lock_hand} "
          f"mask={mask.astype(int).tolist()} start_dof={len(start_full)}")
    try:
        if mode == "cartesian":
            result = planner.plan_cartesian_pose(
                start_full, target, scene_cfg=scene_cfg,
                include_obj_obstacle=include_obj, lock_hand=args.lock_hand,
                return_result=True)
        elif mode == "constrained":
            result = planner.plan_pose_constrained(
                start_full, target, hold_vec_weight=mask,
                scene_cfg=scene_cfg, include_obj_obstacle=include_obj,
                lock_hand=args.lock_hand, return_result=True)
        else:
            assert wrist_start is not None and expected_travel is not None
            result = planner.plan_vertical_stroke(
                start_full, wrist_start, target,
                expected_travel_m=expected_travel,
                travel_tolerance_m=1.0e-5,
                scene_cfg=scene_cfg, include_obj_obstacle=include_obj,
                attached_object_pose_at_start=attached_object_pose,
                label="diagnostic replay", return_result=True)
    except CudaPlanningFault as exc:
        print(f"[diagnose] CUDA_FAULT operation={exc.operation} context={exc.context}")
        print(f"[diagnose] cause={exc.cause!r}")
        return 2

    if mode == "vertical":
        print("[diagnose] "
              f"success={result.success} direction={result.direction} "
              f"failure={result.failure_code} timing={result.timing} "
              f"validation={result.validation}")
    else:
        print("[diagnose] "
              f"success={result.success} stage={result.failure_stage} "
              f"status={result.solver_reported.get('status')} "
              f"hand_lock={result.hand_lock}")
    return 0 if result.success else 1


if __name__ == "__main__":
    raise SystemExit(main())
